server {
    listen 80;
    server_name api.qwikmailer.in;

    location / {
        proxy_pass http://localhost:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Increase max body size for uploads (e.g. CSVs)
        client_max_body_size 50M;
    }
}
