name: Fix Database Schema

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Push DB Schema
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          cd /home/ubuntu/qwikmailer
          
          echo "=== Pushing Database Schema ==="
          pnpm run db:push --filter=@qwikmailer/db
          
          echo "=== Restarting API ==="
          cd apps/api
          pm2 restart api || pm2 start dist/server.js --name api
